ton.py

i am Ton
- Nothing only print ton

<test> commit by ton

---

net.py

<test> pull request

---

add_on.py
main.py
net.py
pun.py

<feat> add_on

---

Passenger.py

<feat> passenger

---

add_on.py
aircraft.py
flight.py

<feat>aircraft,flight

---

booking.py
payment.py
promotion.py
ticket.py

<feat> booking ticket payment

---

airport.py
flight.py
main.py

<feat> serch flight

---

airport.py
main.py

<fix2> search flight

---

airport.py
flight.py
main.py

**ส่วนที่มีการเพิ่ม**
- getter ของ Airport(บางส่วน)
- getter ของ Flight(ทั้งหมด)
- getter ของ FlightInstance(บางส่วน)
- Method create_flight
- Method create_flight_instance

<feat> create flight,create flight instance

---

aircraft.py
airport.py
flight.py
main.py

**สิ่งที่เพิ่ม**
- Method สำหรับสร้างที่นั่ง และ addเข้าAircraft
- Method สำหรับแสดง  ชื่อflight, เวลาขึ้น-ลง
**สิ่งที่แก้**
- แก้ parameter ของ FlightInstance
- แก้วิธีการ add FlightInstance จากการใส่parameter เป็น Object Flight เป็นการใส่ flight.name เนื่องจากเจอบั๊ค

<feat,fix> create seat,show flight ,fix parameter

---

aircraft.py
flight.py
main.py

> show seat ยังไม่ได้ทำ check book

<feat>showseat(all)

---

admin.py
payment.py
promotion.py

เพิ่ม class admin และ method add_promotion,get_promotion

<feat> admin,payment

---

add_on.py
aircraft.py
airport.py
flight.py
main.py

**สิ่งที่เพิ่ม**
- ตัวสร้าง Package
- ตัวแสดง list Package
- ตัวคำนวณราคาเที่ยวบิน + Package
- ตัวโชว์ Flight Detail (อาจใช้ไม่ได้จริงตอนFront end)
- ตัวโชว์Package Detail (อาจใช้ไม่ได้จริงตอนFront end)
- ```eNum``` ของ ```MealType```
- ตัว Select Flight

<feat> Select flight

---

main.py

- เพิ่ม input  จำนวนคน
- รวมshow flight และ show package

<fix> select flight

---

admin.py
flight.py
testadmin.py

ทำ change seat price ไม่ได้เพราะมันเป็น enum
admin เหลือ change seat

<feat> admin, edit_flight_instance, log_in

---

admin.py
aircraft.py
airport.py
booking.py
flight.py
main.py

<feat> select seat

---

add_on.py
booking.py
main.py
ticket.py

>เพิ่มเลือก add_on 
>สร้าง ticket แล้วเอาไปเก็บใน booking เรียบร้อย

<feat> add_on,ticket

---

add_on.py
airport.py
api_ton.py
main.py
testadmin.py
tk_ton.py

ส่วนใหญ่คือทำ api  เพิ่ม/แก้ ในairport  แก้methodในadd_on

<feat> api_ton

---

admin.py
aircraft.py
airport.py
api_pun.py
flight.py
testadmin.py
tk_pun.py

<feat> api_pun

---

Passenger.py
add_on.py
api_bob.py
booking.py
flight.py
main.py
payment.py
promotion.py
ticket.py
tk_bob.py

<feat> passenger api+tk

---

add_on.py
airport.py
api_ton.py
booking.py
flight.py
tk_ton.py

**มาแล้วครับมาแล้ว create booking ที่ทุกคนรอคอย พร้อมทั้ง method search ที่ทุกคนตามหา**
_*และก็ขอแจ้งเพิ่มเติมตอนนี้ ```sum_price```ที่ใช้รวมราคา package กับ flight จาก```class Package``` ย้ายมา```class FlightInstance``` เพราะติดปัญหาเรื่อง circular import_

<feat> create booking

---

api_ton.py
tk_ton.py

<fix> tkinter_ton

---

add_on.py
aircraft.py
booking.py
ticket.py

- **Delete attribute in Ticket** ลบให้ใส่ที่นั่งแค่อันเดียวคือที่  bookseat และในนั้นให้ใส่ instance SeatBook
- **create_seatbook ของ Booking** ```def create_seatbook(self,row,column)``` ใช้สร้างและ add seatbook เข้า list 
parameter ใช้แค่ row column
- **flight_sum_price ของ Booking** ```def flight_sum_price(self)``` รวมราคา flight 
return เป็น list[ ราคารวมของadult, ราคารวมของchild, ราคารวมของinfant] 
- **seat_sum_price ของ Booking** ```def seat_sum_price(self)```  รวมราคาที่นั่ง
return เป็น list ราคาที่นั่งของแต่ละที่นั่ง
- **add_on_sum_price ของ Booking** ```def add_on_sum_price(self)``` รวมราคา add on
return เป็น list ราคาadd on รวมของตั๋วแต่ละใบ
- **sum_price ของ Ticket** ```def sum_price(self,package)``` คำนวณราคาของแต่ละ add on 
return เป็น dict ราคาของแต่ละ Add on

<feat,fix> sum_price,fix_ticket

---

admin.py
airport.py
api_pun.py
booking.py
flight.py
ticket.py
tk_pun.py

<feat,fix>api_pun,tk_pun

---

aircraft.py
api_net.py
api_ton.py
booking.py
flight.py
payment.py

รวมapi net และ ต้น
เพิ่ม payment ใน booking

<fix> add payment to booking

---

api_bob.py
booking.py
flight.py
payment.py
promotion.py
tk_payment.py

- class booking กับ payment binary association กัน ตั้งแต่ตอนที่booking สร้างpayment -> ใช้ id payment = id booking 
- รวมเงินกันที่payment
- หน้า payment เลือกpromotion ได้

<feat> payment fastapi+tk

---

api_ton.py
flight.py
tk.py

<app> complete

---

admin.py
api_pun.py
api_ton.py
booking.py
ticket.py
tk.py

<fix> change_seat

---

tk.py

<fix> tk passenger bug

---

api_ton.py
tk.py

<fix> tk back button bug

---

admin.py
api_ton.py

<fix> admin

---

Passenger.py

ลืมทำ add parent ของ InternaionalPassenger

<fix> passenger international bug

---

admin.py
airport.py
api.py
booking.py
flight.py
payment.py
tk.py

แก้ที่อาจารย์บอก แต่บัคที่เจอวันนี้ตอนส่งจารย์ยังไม่ได้แก้ เปลี่ยนชื่อ airportcatalog เป็น system ละ ถ้าพบบัคเพิ่มแจ้งมาเดี่ยวนั่งดูให้

<fix del> del useless import fix airport

---

booking.py
tk.py

<fix> sumprice bug

---

tk.py

แก้บัคเล็กให้ดักของตรงadd on แจ้งnoti

<fix> tk meal amount bug

---

tk.py

<fix> tk adult list bug
